name: example
description: "모바일통합구현1 1학기 3학년 2반 수업"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  intl: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

